In [1]:
## simulations
import numpy as np
import input_parameters as cont
import differentiation_matrix as diff

In [2]:
## initialize Chebyshev differentiation matrix
x,y = diff.xy_grid()

D = diff.D_matrix(x)
TD = np.transpose(D)

D2 = D*D
TD2 = TD*TD

In [3]:
## boundary conditions

## D
D00 = D[0,0]
Dm0 = D[-1,0]
D0m = D[0,-1]
Dmm = D[-1,-1]

D0k = D[0,1:-1]
Dmk = D[-1,1:-1]




## D transpose
TD00 = TD[0,0]
TD0m = TD[0,-1]
TDm0 = TD[-1,0]
TDmm = TD[-1,-1]

TDk0 = TD[1:-1,0]
TDkm = TD[1:-1,-1]

In [4]:
## Call initialized U,V,T matrices
U0 = diff.U_0()
U1 = U0
V0 = diff.V_0()
V1 = V0
T0 = diff.T_0()
T1 = T0
T2 = T1
P = U1

In [5]:
U0, T0, V0

(matrix([[2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.]]),
 matrix([[ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5]]),
 matrix([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]))

In [6]:
## U orginial BC
Ui0 = U0[:,0]
Uin = U0[:,-1]
U0j = U0[0,:]
Umj = U0[-1,:]

## V original BC
Vi0 = V0[:,:]
Vin = V0[:,-1]
V0j = V0[0,:]
Vmj = V0[-1,:]

In [7]:
U0j, Umj, Ui0, Uin

(matrix([[2750.,    0.,    0.,    0.,    0.,    0.]]),
 matrix([[2750.,    0.,    0.,    0.,    0.,    0.]]),
 matrix([[2750.],
         [2750.],
         [2750.],
         [2750.],
         [2750.],
         [2750.]]),
 matrix([[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]))

In [8]:
## NLT
def NL(U,V,X):
    NLX = np.asmatrix(np.asarray(U) * np.asarray(D*X)) +\
          np.asmatrix(np.asarray(V) * np.asarray(X*TD))
    NLX  = NLX * 2
    return NLX

NL(U0,V0,T0)[:,0]

matrix([[-4.88498131e-12],
        [ 0.00000000e+00],
        [ 3.05311332e-13],
        [-1.52655666e-13],
        [ 6.10622664e-13],
        [-1.46549439e-11]])

In [9]:
def eigens_T():
    eigen_vec_T1  = np.zeros([cont.M+1,cont.M+1])
    eigen_val_T1 = np.zeros([cont.M+1])
    eigen_vec_T2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_T2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])
    
    D00_MM_DM0_0M   = D[0,0]*D[cont.M,cont.M]   - D[cont.M,0]*D[0,cont.M]
    TD00_NN_TD0N_N0 = TD[0,0]*TD[cont.N,cont.N] - TD[0,cont.N]*TD[cont.N,cont.N] 
    
    for i in range(1,cont.M): # Neumann boundary conditions
        tempx[i,1:cont.M] =-D2[i,0] * (D[cont.M,cont.M]*D[0,1:cont.M]-D[0,cont.M]*D[cont.M,1:cont.M])/D00_MM_DM0_0M \
                    +D2[i,cont.M] * (D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M])/D00_MM_DM0_0M 
    tempx[1:cont.M,1:cont.M] = (D2[1:cont.M,1:cont.M] - tempx[1:cont.M,1:cont.M])
    ##tempx[1:cont.M,1:cont.M] = cont.asp**2 * (D2[1:cont.M,1:cont.M] - tempx[1:cont.M,1:cont.M])
                       # Dirichlet boundary conditions 
   
    tempy[1:cont.N,1:cont.N] = TD2[1:cont.N,1:cont.N] 
    ##tempy[1:cont.N,1:cont.N] = cont.asp**2 * TD2[1:cont.N,1:cont.N] 
    
    eigen_val_T1[1:cont.M], eigen_vec_T1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_T2[1:cont.N]  , eigen_vec_T2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N] )

    return eigen_vec_T1, eigen_val_T1, eigen_vec_T2, eigen_val_T2

In [10]:
eigens_T()

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        , -0.68734786,  0.70085317,  0.32956835,  0.16996845,
          0.        ],
        [ 0.        ,  0.16599071, -0.09383407,  0.62560747,  0.68637506,
          0.        ],
        [ 0.        , -0.16599071, -0.09383407, -0.62560747,  0.68637506,
          0.        ],
        [ 0.        ,  0.68734786,  0.70085317, -0.32956835,  0.16996845,
          0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ]]),
 array([  0.        , -68.9464202 , -54.79692289, -10.52024646,
         -2.80307711,   0.        ]),
 array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.58518021, -0.67054171,  0.25231132,  0.13967049,
          0.        ],
        [ 0.        , -0.39694347,  0.22444111,  0.66055961,  0.69317541,
          0.        ],
        [ 0.        ,  

In [11]:
def RHS_T():
    
    RHST = NL(U1,V1,T1) - NL(U0,V0,T0) + ((4*T1 + T0)/2*cont.dt)
    
    for i in range(1,cont.M):
        for j in range(1,cont.N):
            RHST[i,j] -= cont.asp*cont.asp*(T1[i,0]*TD2[0,j] + T1[i,-1]*TD2[-1,j]) 
        
    return RHST

RHS_T()
np.shape(RHS_T())

(6, 6)

In [12]:
RHS_T()

matrix([[ 1.25000000e-03,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00, -1.25000000e-03],
        [ 1.25000000e-03, -4.44773982e+01,  5.12260180e+00,
         -5.12260180e+00,  4.44773982e+01, -1.25000000e-03],
        [ 1.25000000e-03, -4.44773982e+01,  5.12260180e+00,
         -5.12260180e+00,  4.44773982e+01, -1.25000000e-03],
        [ 1.25000000e-03, -4.44773982e+01,  5.12260180e+00,
         -5.12260180e+00,  4.44773982e+01, -1.25000000e-03],
        [ 1.25000000e-03, -4.44773982e+01,  5.12260180e+00,
         -5.12260180e+00,  4.44773982e+01, -1.25000000e-03],
        [ 1.25000000e-03,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00, -1.25000000e-03]])

In [13]:
def eigens_P():
    eigen_vec_P1  = np.zeros([cont.M+1,cont.M+1])
    eigen_val_P1 = np.zeros([cont.M+1])
    eigen_vec_P2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_P2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])
  
    D00_MM_DM0_0M   = D[0,0]*D[cont.M,cont.M]   - D[cont.M,0]*D[0,cont.M]
    TD00_NN_TD0N_N0 = TD[0,0]*TD[cont.N,cont.N] - TD[0,cont.N]*TD[cont.N,0]
    
    for i in range(cont.M): # generate the coefficient matrix column-wise
        tempx[i,1:cont.M] = -D2[i,0] * (D[cont.M,cont.M]*D[0,1:cont.M]-D[0,cont.M]*D[cont.M,1:cont.M])/D00_MM_DM0_0M \
                          + D2[i,cont.M] * (D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M])/D00_MM_DM0_0M 
    tempx[1:cont.M,1:cont.N] = (D2[1:cont.M,1:cont.N] + tempx[1:cont.M,1:cont.N])
    ##tempx[1:cont.M,1:cont.N] = cont.asp**2*(D2[1:cont.M,1:cont.N] + tempx[1:cont.M,1:cont.N])
    
    for j in range(cont.M): # generate the coefficient matrix column-wise
        tempy[1:cont.N,j] = np.asarray(np.transpose(-(TD2[0,j] * (TD[cont.N,cont.N]*TD[1:cont.N,0]-TD[cont.N,0]*TD[1:cont.N,cont.N])/TD00_NN_TD0N_N0) \
                          + (TD2[cont.N,j] * (TD[0,cont.N]*TD[1:cont.N,0]-TD[0,0]*TD[1:cont.N,cont.N])/TD00_NN_TD0N_N0)))
    tempy[1:cont.M,1:cont.N] = (TD2[1:cont.M,1:cont.N] + tempy[1:cont.M,1:cont.N])
    ##tempy[1:cont.M,1:cont.N] = cont.asp**2*(TD2[1:cont.M,1:cont.N] + tempy[1:cont.M,1:cont.N])
    
    eigen_val_P1[1:cont.M], eigen_vec_P1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_P2[1:cont.N], eigen_vec_P2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N])
    
    return eigen_vec_P1, eigen_val_P1, eigen_vec_P2, eigen_val_P2

In [14]:
eigens_P()

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.28990341, -0.56825633, -0.63526566,  0.5       ,
          0.        ],
        [ 0.        , -0.64494652,  0.42081438, -0.31054394,  0.5       ,
          0.        ],
        [ 0.        ,  0.64494652,  0.42081438,  0.31054394,  0.5       ,
          0.        ],
        [ 0.        , -0.28990341, -0.56825633,  0.63526566,  0.5       ,
          0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ]]),
 array([ 0.00000000e+00, -1.72615598e+01, -9.60000000e+00, -2.47177353e+00,
        -6.71357067e-16,  0.00000000e+00]),
 array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.31054394, -0.5       ,  0.42081438, -0.64494652,
          0.        ],
        [ 0.        , -0.63526566,  0.5       ,  0.56825633, -0.28990341,
          0.        ],
     

In [15]:
def RHS_P():
    
    RHSP1 = cont.asp*D*(-2*NL(U1,V1,U1) + NL(U0,V0,U0))
    RHSP2 = cont.asp*((-2*NL(U1,V1,V1) + NL(U0,V0,V0) + cont.Ri*cont.Re*cont.Re*T2)*TD)

    RHSP = np.empty_like(D2[1:-1,1:-1])    
    for i in range(1,cont.M):
        for j in range(1,cont.M):
            RHSP[i-1,j-1] = RHSP1[i,j] + RHSP2[i,j] - cont.asp*(D2[i,0]*((RHSP1[0,j]*Dmm -  RHSP1[-1,j]*D0m)/(D00*Dmm - D0m*Dm0)) + D2[i,-1]*((RHSP1[0,j]*Dm0 -  RHSP1[-1,j]*D00)/(Dm0*D0m - D00*Dmm)) + TD2[0,j]*((RHSP2[i,0]*TDmm - RHSP2[i,-1]*TDm0)/(TD00*TDmm - TD0m*TDm0)) + TD2[-1,i]*(RHSP2[i,0]*TD0m - RHSP2[i,-1]*TD00)/(TD0m*TDm0 - TD00*TDmm))
    
    return RHSP

RHSP = RHS_P()
np.shape(RHSP)

(4, 4)

In [16]:
RHS_P()

matrix([[-3186516.65454706,   109445.52815968,  -277951.23281421,
           177086.58447905],
        [-2934402.0062119 ,   361560.17649484,   -25836.58447905,
           429201.23281421],
        [-3321798.76718579,   -25836.58447905,  -413233.34545294,
            41804.47184032],
        [  177086.58447905,  3473048.76718579,  3085652.0062119 ,
          3540689.82350516]])

In [17]:
def eigens_vel():
    eigen_vec_vel1  = np.zeros([cont.M,cont.M+1])
    eigen_val_vel1 = np.zeros([cont.M+1])
    eigen_vec_vel2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_vel2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])

    tempx[1:cont.M,1:cont.N]  = D2[1:cont.M,1:cont.N] 
    tempy[1:cont.N,1:cont.N]  =  TD2[1:cont.N,1:cont.N] 

    eigen_val_vel1[1:cont.M], eigen_vec_vel1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_vel2[1:cont.N], eigen_vec_vel2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N] )

    return eigen_vec_vel1, eigen_val_vel1, eigen_vec_vel2, eigen_val_vel2

In [18]:
eigens_vel()

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.66055961, -0.69317541,  0.39694347,  0.22444111,
          0.        ],
        [ 0.        , -0.25231132,  0.13967049,  0.58518021,  0.67054171,
          0.        ],
        [ 0.        ,  0.25231132,  0.13967049, -0.58518021,  0.67054171,
          0.        ],
        [ 0.        , -0.66055961, -0.69317541, -0.39694347,  0.22444111,
          0.        ]]),
 array([  0.        , -40.        , -31.13317829,  -9.6       ,
         -2.46682171,   0.        ]),
 array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.58518021, -0.67054171,  0.25231132,  0.13967049,
          0.        ],
        [ 0.        , -0.39694347,  0.22444111,  0.66055961,  0.69317541,
          0.        ],
        [ 0.        ,  0.39694347,  0.22444111, -0.66055961,  0.69317541,
          0.        ],
        [ 0.        , -

In [19]:
def RHS_U():

    RHSU = cont.asp*D*P + 2*NL(U1,V1,U1) - NL(U0,V0,U0) + ((4*U1 - U0)/2*cont.dt) - cont.Ri*cont.Re*cont.Re*T2
    RHSV = cont.asp*P*TD + NL(U1,V1,V1) - NL(U0,V0,V0) + ((4*V1 + V0)/2*cont.dt) - cont.Ri*cont.Re*cont.Re*T2
    
    for i in range(1,cont.M):
        for j in range(1,cont.N):
            RHSU[i,j] -= cont.asp*cont.asp*(D2[i,0]*U0j[0,j] + D2[i,-1]*Umj[0,j] + Ui0[i,0]*TD2[0,j] + Uin[i,0]*TD2[-1,j])    
            RHSV[i,j] -= cont.asp*cont.asp*(D2[i,0]*V0j[0,j] + D2[i,-1]*Vmj[0,j] + Vi0[i,0]*TD2[0,j] + Vin[i,0]*TD2[-1,j])

    return RHSU, RHSV

RHSU, RHSV = RHS_U()
np.shape(RHSU), np.shape(RHSV)

((6, 6), (6, 6))

In [20]:
def eigens_phi():
    eigen_vec_phi1  = np.zeros([cont.M+1,cont.M+1])
    eigen_val_phi1 = np.zeros([cont.M+1])
    eigen_vec_phi2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_phi2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])
  
    D00_MM_DM0_0M   = D[0,0]*D[cont.M,cont.M]   - D[cont.M,0]*D[0,cont.M]
    TD00_NN_TD0N_N0 = TD[0,0]*TD[cont.N,cont.N] - TD[0,cont.N]*TD[cont.N,0]
    
    for i in range(cont.M): # generate the coefficient matrix column-wise
        tempx[i,1:cont.M] = -D2[i,0] * (D[cont.M,cont.M]*D[0,1:cont.M]-D[0,cont.M]*D[cont.M,1:cont.M])/D00_MM_DM0_0M \
                          + D2[i,cont.M] * (D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M])/D00_MM_DM0_0M 
    tempx[1:cont.M,1:cont.N] = (D2[1:cont.M,1:cont.N] + tempx[1:cont.M,1:cont.N])
    ##tempx[1:cont.M,1:cont.N] = cont.asp**2*(D2[1:cont.M,1:cont.N] + tempx[1:cont.M,1:cont.N])
    
    for j in range(cont.M): # generate the coefficient matrix column-wise
        tempy[1:cont.N,j] = np.asarray(np.transpose(-(TD2[0,j] * (TD[cont.N,cont.N]*TD[1:cont.N,0]-TD[cont.N,0]*TD[1:cont.N,cont.N])/TD00_NN_TD0N_N0) \
                          + (TD2[cont.N,j] * (TD[0,cont.N]*TD[1:cont.N,0]-TD[0,0]*TD[1:cont.N,cont.N])/TD00_NN_TD0N_N0)))
    tempy[1:cont.M,1:cont.N] = (TD2[1:cont.M,1:cont.N] + tempy[1:cont.M,1:cont.N])
    ##tempy[1:cont.M,1:cont.N] = cont.asp**2*(TD2[1:cont.M,1:cont.N] + tempy[1:cont.M,1:cont.N])
    
    eigen_val_phi1[1:cont.M], eigen_vec_phi1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_pih2[1:cont.N], eigen_vec_phi2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N])
    
    return eigen_vec_phi1, eigen_val_phi1, eigen_vec_phi2, eigen_val_phi2

In [21]:
def RHS_Z(U, V):
    
    RHSZ = cont.asp*(D*U + V*TD)
    RHSZ *= 0.25

    return RHSZ

RHSZ = RHS_Z(U1,V1)
np.shape(RHSZ)

(6, 6)

In [22]:
RHS_Z(U0, V0)

matrix([[-3.63797881e-12,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 2.36477504e-13,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 2.22821761e-13,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 4.17998969e-14,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-7.73070497e-12,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])