In [1]:
## simulations
import numpy as np
import input_parameters as cont
import differentiation_matrix as diff

In [2]:
## initialize Chebyshev differentiation matrix
x,y = diff.xy_grid()

D = diff.D_matrix(x)
TD = np.transpose(D)

D2 = D*D
TD2 = TD*TD

In [3]:
## boundary conditions

## D
D00 = D[0,0]
Dm0 = D[-1,0]
D0m = D[0,-1]
Dmm = D[-1,-1]

D0k = D[0,1:-1]
Dmk = D[-1,1:-1]




## D transpose
TD00 = TD[0,0]
TD0m = TD[0,-1]
TDm0 = TD[-1,0]
TDmm = TD[-1,-1]

TDk0 = TD[1:-1,0]
TDkm = TD[1:-1,-1]

In [4]:
## Call initialized U,V,T matrices
U0 = diff.U_0()
U1 = U0
V0 = diff.V_0()
V1 = V0
T0 = diff.T_0()
T1 = T0
T2 = T1
P = U1

In [5]:
U0, T0, V0

(matrix([[2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.],
         [2750.,    0.,    0.,    0.,    0.,    0.]]),
 matrix([[ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5],
         [ 0.5,  0. ,  0. ,  0. ,  0. , -0.5]]),
 matrix([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]))

In [6]:
## U orginial BC
Ui0 = U0[0,:]
Uin = U0[-1,:]
U0j = U0[:,0]
Umj = U0[:,-1]

## V original BC
Vi0 = V0[0,:]
Vin = V0[-1,:]
V0j = V0[:,0]
Vmj = V0[:,-1]


In [7]:
U0j, Umj, Ui0, Uin

(matrix([[2750.],
         [2750.],
         [2750.],
         [2750.],
         [2750.],
         [2750.]]), matrix([[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]), matrix([[2750.,    0.,    0.,    0.,    0.,    0.]]), matrix([[2750.,    0.,    0.,    0.,    0.,    0.]]))

In [8]:
## NLT
def NL(U,V,X):
    NLX = np.asmatrix(np.asarray(U) * np.asarray(D*X)) +\
          np.asmatrix(np.asarray(V) * np.asarray(X*TD))
    NLX  = NLX * 2
    return NLX

NL(U0,V0,T0)[:,0]

matrix([[-4.88498131e-12],
        [ 0.00000000e+00],
        [ 3.05311332e-13],
        [-1.52655666e-13],
        [ 6.10622664e-13],
        [-1.46549439e-11]])

In [9]:
def eigens_T():
    eigen_vec_T1  = np.zeros([cont.M+1,cont.M+1])
    eigen_val_T1 = np.zeros([cont.M+1])
    eigen_vec_T2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_T2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])
    D00_MM_DM0_0M   = D[0,0]*D[cont.M,cont.M]   - D[cont.M,0]*D[0,cont.M]
    TD00_NN_TD0N_N0 = TD[0,0]*TD[cont.N,cont.N] - TD[0,cont.N]*TD[cont.N,cont.N] 
    for i in range(1,cont.M): # Neumann boundary conditions
        tempx[i,1:cont.M] =-D2[i,0] * (D[cont.M,cont.M]*D[0,1:cont.M]-D[0,cont.M]*D[cont.M,1:cont.M])/D00_MM_DM0_0M \
                    +D2[i,cont.M] * (D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M])/D00_MM_DM0_0M 
    tempx[1:cont.M,1:cont.M] = cont.asp**2 * (D2[1:cont.M,1:cont.M] - tempx[1:cont.M,1:cont.M])
                       # Dirichlet boundary conditions 
    tempy[1:cont.N,1:cont.N] = cont.asp**2 * TD2[1:cont.N,1:cont.N] 
    eigen_val_T1[1:cont.M], eigen_vec_T1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_T2[1:cont.N]  , eigen_vec_T2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N] )

    return eigen_vec_T1, eigen_val_T1, eigen_vec_T2, eigen_val_T2

In [10]:
eigens_T()

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        , -0.68734786,  0.70085317,  0.32956835,  0.16996845,
          0.        ],
        [ 0.        ,  0.16599071, -0.09383407,  0.62560747,  0.68637506,
          0.        ],
        [ 0.        , -0.16599071, -0.09383407, -0.62560747,  0.68637506,
          0.        ],
        [ 0.        ,  0.68734786,  0.70085317, -0.32956835,  0.16996845,
          0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ]]),
 array([   0.        , -275.78568081, -219.18769158,  -42.08098586,
         -11.21230842,    0.        ]),
 array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.58518021, -0.67054171,  0.25231132,  0.13967049,
          0.        ],
        [ 0.        , -0.39694347,  0.22444111,  0.66055961,  0.69317541,
          0.        ],
        [ 0.     

In [11]:
## right hand side of Temportal Scheme
def RHS_T():
    
    RHST = NL(U1,V1,T1) - NL(U0,V0,T0) + ((4*T1 + T0)/2*cont.dt)
    
    for i in range(1,cont.M):
        for j in range(1,cont.M):
            RHST[i,j] -= cont.asp*cont.asp*(T1[i,0]*TD2[0,j] + T1[i,-1]*TD2[-1,j]) 
        
    return RHST

RHS_T()
np.shape(RHS_T())

(6, 6)

In [14]:
def eigens_vel():
    eigen_vec_vel1  = np.zeros([cont.M,cont.M+1])
    eigen_val_vel1 = np.zeros([cont.M+1])
    eigen_vec_vel2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_vel2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])

    tempx[1:cont.M,1:cont.N]  = D2[1:cont.M,1:cont.N] 
    tempy[1:cont.N,1:cont.N]  =  TD2[1:cont.N,1:cont.N] 

    eigen_val_vel1[1:cont.M], eigen_vec_vel1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_vel2[1:cont.N], eigen_vec_vel2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N] )

    return eigen_vec_vel1, eigen_val_vel1, eigen_vec_vel2, eigen_val_vel2

In [ ]:
eigens_vel()