In [1]:
## simulations
import numpy as np
import input_parameters as cont
import differentiation_matrix as diff

In [2]:
## initialize Chebyshev differentiation matrix
x,y = diff.xy_grid()

D = diff.D_matrix(x)
TD = np.transpose(D)

D2 = D*D
TD2 = TD*TD

In [3]:
## boundary conditions

## D
D00 = D[0,0]
Dm0 = D[-1,0]
D0m = D[0,-1]
Dmm = D[-1,-1]

D0k = D[0,1:-1]
Dmk = D[-1,1:-1]




## D transpose
TD00 = TD[0,0]
TD0m = TD[0,-1]
TDm0 = TD[-1,0]
TDmm = TD[-1,-1]

TDk0 = TD[1:-1,0]
TDkm = TD[1:-1,-1]

In [4]:
## Call initialized U,V,T matrices
## U0,U1,U2 at t = 0
U0 = diff.U_0(x)
U1 = U0
U2 = U0

## V0,V1,V2 at t = 0
V0 = diff.V_0()
V1 = V0
V2 = V0

## T0,T1,T2 at t = 0
T0 = np.asmatrix(np.zeros([cont.M+1,cont.M+1]))
T1 = diff.T_0()
T2 = T0

U0[:,0] = 0
for j in range(1,cont.M): 
    T1[:,j] = y[j]
    
Uexact = diff.U_0(x)
Vexact = np.asmatrix(np.zeros([cont.M+1,cont.N+1]))   

In [5]:
U0, T0, V0

(matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]))

In [6]:
U1, T1, V1

(matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 matrix([[  5.00000000e-01,   4.33012702e-01,   2.50000000e-01,
            3.06161700e-17,  -2.50000000e-01,  -4.33012702e-01,
           -5.00000000e-01],
         [  5.00000000e-01,   4.33012702e-01,   2.50000000e-01,
            3.06161700e-17,  -2.50000000e-01,  -4.33012702e-01,
           -5.00000000e-01],
         [  5.00000000e-01,   4.33012702e-01,   2.50000000e-01,
            3.06161700e-17,  -2.50000000e-01,  -4.33012702e-01,
           -5.00000000e-01],
         [  5.00000000e-01,   4.33012702e-01,   2.50000000e-01,
            3.06161700e-17,  -2.50000000e-01,  -4.33012702e-01,
           -5.00000000e-01],
         [  5.00000000e-01,   4.33012702e-01,   

In [7]:
## U orginial BC
Ui0 = U0[:,0]
Uin = U0[:,-1]
U0j = U0[0,:]
Umj = U0[-1,:]

## V original BC
Vi0 = V0[:,:]
Vin = V0[:,-1]
V0j = V0[0,:]
Vmj = V0[-1,:]

In [8]:
U0j, Umj, Ui0, Uin

(matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 matrix([[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]]),
 matrix([[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]]))

In [9]:
## NLT
def NL(U,V,X):
    NLX = np.asmatrix(np.asarray(U) * np.asarray(D*X)) +\
          np.asmatrix(np.asarray(V) * np.asarray(X*TD))
    NLX  = NLX * 2
    return NLX

NL(U0,V0,T0)[:,0]

matrix([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [10]:
def LU(U,V):
    LU = (U*TD2) - (D*V)*TD
    LU = LU * 4
    return LU

def LV(U,V):
    LV = (D2*V) - (D)*(U*TD)
    LV = LV * 4
    return LV

#LU(U1,V1), LV(U1,V1)

In [11]:
def eigens_T():
    eigen_vec_T1  = np.zeros([cont.M+1,cont.M+1])
    eigen_val_T1 = np.zeros([cont.M+1])
    eigen_vec_T2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_T2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])
    
    D00_MM_DM0_0M   = D[0,0]*D[cont.M,cont.M]   - D[cont.M,0]*D[0,cont.M]
    TD00_NN_TD0N_N0 = TD[0,0]*TD[cont.N,cont.N] - TD[0,cont.N]*TD[cont.N,cont.N] 
    
    for i in range(1,cont.M): # Neumann boundary conditions
        tempx[i,1:cont.M] =-D2[i,0] * (D[cont.M,cont.M]*D[0,1:cont.M]-D[0,cont.M]*D[cont.M,1:cont.M])/D00_MM_DM0_0M \
                           +D2[i,cont.M] * (D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M])/D00_MM_DM0_0M 
    tempx[1:cont.M,1:cont.M] = cont.asp**2 * (D2[1:cont.M,1:cont.M] + tempx[1:cont.M,1:cont.M])
                       # Dirichlet boundary conditions 
   
    tempy[1:cont.N,1:cont.N] = cont.asp**2 * TD2[1:cont.N,1:cont.N] 
    
    eigen_val_T1[1:cont.M], eigen_vec_T1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_T2[1:cont.N]  , eigen_vec_T2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N] )

    return eigen_vec_T1, eigen_val_T1, eigen_vec_T2, eigen_val_T2

In [12]:
eigens_T()

(array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,  -2.48151635e-01,   4.93291351e-01,
          -5.59384051e-01,  -4.47213595e-01,  -5.72984105e-01,
           0.00000000e+00],
        [  0.00000000e+00,   5.57644495e-01,  -5.06619821e-01,
          -6.65576838e-03,  -4.47213595e-01,  -4.14353974e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -5.04882924e-01,  -1.79361931e-15,
           6.11629273e-01,  -4.47213595e-01,  -1.29169494e-15,
           0.00000000e+00],
        [  0.00000000e+00,   5.57644495e-01,   5.06619821e-01,
          -6.65576838e-03,  -4.47213595e-01,   4.14353974e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -2.48151635e-01,  -4.93291351e-01,
          -5.59384051e-01,  -4.47213595e-01,   5.72984105e-01,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.

In [13]:
def RHS_T():
    
    RHST = cont.Pr*(2*NL(U1,V1,T1) - NL(U0,V0,T0) - ( (4*T1 - T0)/(2*cont.dt) ) )
    
    for j in range(1,cont.M):
        for i in range(1,cont.N):
            RHST[i,j] = RHST[i,j] - cont.asp*cont.asp*(T1[i,0]*TD2[0,j] + T1[i,-1]*TD2[-1,j]) 
            ##RHST[i,j] = RHST[i,j] - (T1[i,0]*TD2[0,j] + T1[i,-1]*TD2[-1,j]) 
        
    return RHST

RHS_T()
np.shape(RHS_T())

(7, 7)

In [14]:
RHS_T()

matrix([[ -1.00000000e+03,  -8.66025404e+02,  -5.00000000e+02,
          -6.12323400e-14,   5.00000000e+02,   8.66025404e+02,
           1.00000000e+03],
        [ -1.00000000e+03,  -9.49163843e+02,  -4.94666667e+02,
          -5.10182881e-14,   4.94666667e+02,   9.49163843e+02,
           1.00000000e+03],
        [ -1.00000000e+03,  -9.49163843e+02,  -4.94666667e+02,
          -5.10182881e-14,   4.94666667e+02,   9.49163843e+02,
           1.00000000e+03],
        [ -1.00000000e+03,  -9.49163843e+02,  -4.94666667e+02,
          -5.10182881e-14,   4.94666667e+02,   9.49163843e+02,
           1.00000000e+03],
        [ -1.00000000e+03,  -9.49163843e+02,  -4.94666667e+02,
          -5.10182881e-14,   4.94666667e+02,   9.49163843e+02,
           1.00000000e+03],
        [ -1.00000000e+03,  -9.49163843e+02,  -4.94666667e+02,
          -5.10182881e-14,   4.94666667e+02,   9.49163843e+02,
           1.00000000e+03],
        [ -1.00000000e+03,  -8.66025404e+02,  -5.00000000e+02,
          -6.

In [15]:
def Helmholtz_solver(RHS,sigma,eig_val1,eig_vec1,eig_val2,eig_vec2):
    tol = 1e-10
    tempX = np.zeros([cont.M+1,cont.N+1])
    tempH = np.zeros([cont.M+1,cont.N+1])
    X = np.zeros([cont.M+1,cont.N+1])
    
    tempH[1:cont.M,1:cont.M] = np.linalg.solve(eig_vec1[1:cont.M,1:cont.M],RHS[1:cont.M,1:cont.M])
    tempH[1:cont.M,1:cont.M] = np.matmul(tempH[1:cont.M,1:cont.M],eig_vec2[1:cont.M,1:cont.M])
    
    for j in range(1,cont.N):
        for i in range(1,cont.M):
            if abs(eig_val1[i])<tol and abs(eig_val2[j])<tol and abs(sigma)<tol:
                X[i,j] = 0.0
            else:
                X[i,j] = tempH[i,j]/(eig_val1[i]+eig_val2[j]-sigma)
 
    tempX[1:cont.M,1:cont.N] = np.linalg.solve(np.transpose(eig_vec2[1:cont.M,1:cont.N]),np.transpose(X[1:cont.M,1:cont.N]))
    tempX[1:cont.M,1:cont.N] = np.transpose(tempX[1:cont.M,1:cont.N])
    X[1:cont.M,1:cont.N] = np.matmul(eig_vec1[1:cont.M,1:cont.N],tempX[1:cont.M,1:cont.N])
  
    return X

In [16]:
RHS = RHS_T()
sigma = 3.0*cont.Pr/(2.0*cont.dt)
eig_vec1, eig_val1, eig_vec2, eig_val2 = eigens_T()
eig_vec1, eig_val1, eig_vec2, eig_val2

(array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,  -2.48151635e-01,   4.93291351e-01,
          -5.59384051e-01,  -4.47213595e-01,  -5.72984105e-01,
           0.00000000e+00],
        [  0.00000000e+00,   5.57644495e-01,  -5.06619821e-01,
          -6.65576838e-03,  -4.47213595e-01,  -4.14353974e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -5.04882924e-01,  -1.79361931e-15,
           6.11629273e-01,  -4.47213595e-01,  -1.29169494e-15,
           0.00000000e+00],
        [  0.00000000e+00,   5.57644495e-01,   5.06619821e-01,
          -6.65576838e-03,  -4.47213595e-01,   4.14353974e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -2.48151635e-01,  -4.93291351e-01,
          -5.59384051e-01,  -4.47213595e-01,   5.72984105e-01,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.

In [17]:
c1 = D[0,0]*D[-1,-1] - D[-1,0]*D[0,-1]
c2 = -c1
c3 = TD[0,0]*D[-1,-1] - TD[0,-1]*TD[-1,0]
c4 = -c3

In [18]:
c1, c2, c3, c4

(-147.77777777777777,
 147.77777777777777,
 -147.77777777777777,
 147.77777777777777)

In [19]:
def T():
    Tnew = np.zeros([cont.M+1,cont.N+1])
    RHS = RHS_T()
    sigma = 3.0*cont.Pr/(2.0*cont.dt)
    eig_vec1, eig_val1, eig_vec2, eig_val2 = eigens_T()
    Tnew=Helmholtz_solver(RHS,sigma,eig_val1,eig_vec1,eig_val2,eig_vec2)
    for j in range(1,cont.M):      # c1 and c2 need to be defined
        Tnew[0,j] = np.dot(D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M],Tnew[1:cont.M,j])/c1
        Tnew[-1,j]= np.dot(D[cont.M,cont.M]*D[0,1:cont.M]-D[0,cont.M]*D[cont.M,1:cont.M],Tnew[1:cont.M,j])/c2
  # update top and bottom boundaries    
    Tnew[:,0] = 0.5
    Tnew[:,-1] = -0.5
    return Tnew

In [20]:
T2 = np.asmatrix(T())
T2

matrix([[  5.00000000e-01,   5.61455357e-01,   3.34002895e-01,
           3.97872599e-17,  -3.34002895e-01,  -5.61455357e-01,
          -5.00000000e-01],
        [  5.00000000e-01,   5.61455357e-01,   3.34002895e-01,
           3.93777105e-17,  -3.34002895e-01,  -5.61455357e-01,
          -5.00000000e-01],
        [  5.00000000e-01,   5.61455357e-01,   3.34002895e-01,
           3.79670574e-17,  -3.34002895e-01,  -5.61455357e-01,
          -5.00000000e-01],
        [  5.00000000e-01,   5.61455357e-01,   3.34002895e-01,
           3.82097821e-17,  -3.34002895e-01,  -5.61455357e-01,
          -5.00000000e-01],
        [  5.00000000e-01,   5.61455357e-01,   3.34002895e-01,
           3.79670574e-17,  -3.34002895e-01,  -5.61455357e-01,
          -5.00000000e-01],
        [  5.00000000e-01,   5.61455357e-01,   3.34002895e-01,
           3.93777105e-17,  -3.34002895e-01,  -5.61455357e-01,
          -5.00000000e-01],
        [  5.00000000e-01,   5.61455357e-01,   3.34002895e-01,
           3.

In [21]:
def eigens_P():
    eigen_vec_P1  = np.zeros([cont.M+1,cont.M+1])
    eigen_val_P1 = np.zeros([cont.M+1])
    eigen_vec_P2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_P2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])
  
    D00_MM_DM0_0M   = D[0,0]*D[cont.M,cont.M]   - D[cont.M,0]*D[0,cont.M]
    TD00_NN_TD0N_N0 = TD[0,0]*TD[cont.N,cont.N] - TD[0,cont.N]*TD[cont.N,0]
    
    for i in range(cont.M): # generate the coefficient matrix column-wise
        tempx[i,1:cont.M] = -D2[i,0] * (D[cont.M,cont.M]*D[0,1:cont.M]-D[0,cont.M]*D[cont.M,1:cont.M])/D00_MM_DM0_0M \
                          + D2[i,cont.M] * (D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M])/D00_MM_DM0_0M 
    ##tempx[1:cont.M,1:cont.N] = (D2[1:cont.M,1:cont.N] + tempx[1:cont.M,1:cont.N])
    tempx[1:cont.M,1:cont.N] = cont.asp**2*(D2[1:cont.M,1:cont.N] + tempx[1:cont.M,1:cont.N])
    
    for j in range(cont.M): # generate the coefficient matrix column-wise
        tempy[1:cont.N,j] = np.asarray(np.transpose(-(TD2[0,j] * (TD[cont.N,cont.N]*TD[1:cont.N,0]-TD[cont.N,0]*TD[1:cont.N,cont.N])/TD00_NN_TD0N_N0) \
                          + (TD2[cont.N,j] * (TD[0,cont.N]*TD[1:cont.N,0]-TD[0,0]*TD[1:cont.N,cont.N])/TD00_NN_TD0N_N0)))
    ##tempy[1:cont.M,1:cont.N] = (TD2[1:cont.M,1:cont.N] + tempy[1:cont.M,1:cont.N])
    tempy[1:cont.M,1:cont.N] = cont.asp**2*(TD2[1:cont.M,1:cont.N] + tempy[1:cont.M,1:cont.N])
    
    eigen_val_P1[1:cont.M], eigen_vec_P1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_P2[1:cont.N], eigen_vec_P2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N])
    
    return eigen_vec_P1, eigen_val_P1, eigen_vec_P2, eigen_val_P2

In [22]:
eigens_P()

(array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,  -2.48151635e-01,   4.93291351e-01,
          -5.59384051e-01,  -4.47213595e-01,  -5.72984105e-01,
           0.00000000e+00],
        [  0.00000000e+00,   5.57644495e-01,  -5.06619821e-01,
          -6.65576838e-03,  -4.47213595e-01,  -4.14353974e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -5.04882924e-01,  -1.79361931e-15,
           6.11629273e-01,  -4.47213595e-01,  -1.29169494e-15,
           0.00000000e+00],
        [  0.00000000e+00,   5.57644495e-01,   5.06619821e-01,
          -6.65576838e-03,  -4.47213595e-01,   4.14353974e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -2.48151635e-01,  -4.93291351e-01,
          -5.59384051e-01,  -4.47213595e-01,   5.72984105e-01,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.

In [23]:
def RHS_P():
    
    RHS = np.asmatrix(np.zeros([cont.M+1,cont.N+1]))
    rhs1= np.asmatrix(np.zeros([cont.M+1,cont.N+1]))
    rhs2= np.asmatrix(np.zeros([cont.M+1,cont.N+1]))

    
    RHS = cont.asp*D*( -2*NL(U1,V1,U1) + NL(U0,V0,U0) )\
        + cont.asp*( -2*NL(U1,V1,V1) + NL(U0,V0,V0) + cont.Ri*cont.Re*cont.Re*T2)*TD 
    rhs1[0,:] =(-3*Uexact[0,:]+4*U1[0,:]-U0[0,:]) / (2.0*cont.dt) \
              + (-2*NL(U1,V1,U1))[0,:] + NL(U0,V0,U0)[0,:] +2*LU(U1,V1)[0,:]-LU(U0,V0)[0,:]
    rhs1[-1,:]=(-3*Uexact[-1,:]+4*U1[-1,:]-U0[-1,:]) / (2.0*cont.dt) \
              + (-2*NL(U1,V1,U1))[-1,:] + NL(U0,V0,U0)[-1,:] +2*LU(U1,V1)[-1,:]-LU(U0,V0)[-1,:]
    rhs2[:,0] =(-3*Vexact[:,0]+4*V1[:,0]-V0[:,0]) / (2.0*cont.dt) \
              + (-2*NL(U1,V1,V1))[:,0] + NL(U0,V0,V0)[:,0] +2*LV(U1,V1)[:,0]\
              -LV(U0,V0)[:,0]+ cont.Ri*cont.Re*cont.Re*T2[:,0]
    rhs2[:,-1]=(-3*Vexact[:,-1]+4*V1[:,-1]-V0[:,-1]) / (2.0*cont.dt) \
              + (-2*NL(U1,V1,V1))[:,-1] + NL(U0,V0,V0)[:,-1] +2*LV(U1,V1)[:,-1]\
              -LV(U0,V0)[:,-1] + cont.Ri*cont.Re*cont.Re*T2[:,-1]
            
    for j in range(1,cont.M):  # c1,c2,c3,c4 need to be defined
        RHS[:,j] = RHS[:,j]-cont.asp*D2[:,0] *(D[cont.M,cont.N]*rhs1[0,j] -D[0,cont.M]*rhs1[cont.M,j] ) / c1 \
                          -cont.asp*D2[:,cont.M]  *(D[cont.M,0]*rhs1[0,j] -D[0,0]*rhs1[cont.N,j] ) / c2 \
                          -2*TD2[0,j]  *(TD[cont.M,cont.M]*rhs2[:,0] -TD[cont.M,0]*rhs2[:,cont.M] )/ c3 \
                          -2*TD2[cont.M,j]  *(TD[0,cont.M]*rhs2[:,0] -TD[0,0]*rhs2[:,cont.M] )/ c4
    RHS = np.asarray(RHS)
    return rhs1, rhs2, RHS


In [24]:
RHS_P()

(matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 matrix([[ 3781250.,        0.,        0.,        0.,        0.,        0.,
          -3781250.],
         [ 3781250.,        0.,        0.,        0.,        0.,        0.,
          -3781250.],
         [ 3781250.,        0.,        0.,        0.,        0.,        0.,
          -3781250.],
         [ 3781250.,        0.,        0.,        0.,        0.,        0.,
          -3781250.],
         [ 3781250.,        0.,        0.,        0.,        0.,        0.,
          -3781250.],
         [ 3781250.,        0.,        0.,        0.,        0.,        0.,
          -3781250.],
         [ 3781250.,        0.,        0.,        0.,        0.,        0.,
          -3

In [25]:
def Pressure():
    P = np.asmatrix(np.zeros([cont.M+1,cont.N+1]))
    rhs1, rhs2, RHS = RHS_P()
    eig_vec1, eig_val1, eig_vec2, eig_val2 = eigens_P()
    sigma=0.0
    P=Helmholtz_solver(RHS,sigma,eig_val1,eig_vec1,eig_val2,eig_vec2)
    P[:,0] = 0
    P[:,cont.M] = 0
    for j in range(1,cont.M):
        P[0,j]=((D[cont.M,cont.M]*0.5*rhs1[0,j]- D[0,cont.M]*0.5*rhs1[cont.M,j]) 
                 -np.dot(D[cont.M,cont.M]*D[0,1:cont.N]-D[0,cont.M]*D[cont.M,1:cont.M], P[1:cont.M,j])) / c1
        
        P[cont.M,j]=((D[cont.M,0]*0.5*rhs1[0,j]- D[0,0]*0.5*rhs1[cont.M,j]) 
                 -np.dot(D[cont.N,0]*D[0,1:cont.N]-D[0,0]*D[cont.N,1:cont.N], P[1:cont.M,j])) / c2

    for i in range(0,cont.M+1):
        P[i,0]     =( (TD[cont.M,cont.M]*0.5*rhs2[i,0] -TD[cont.M,0]*0.5*rhs2[i,cont.M])
                 - np.dot(P[i,1:cont.M], TD[cont.M,cont.M]*TD[1:cont.M,0]-TD[cont.M,0]*TD[1:cont.M,cont.M]) )/c3
        
        P[i,cont.M]=( (TD[0,cont.M]     *0.5*rhs2[i,0] -TD[0,0]    *0.5*rhs2[i,cont.M])
                 - np.dot(P[i,1:cont.M], TD[0,cont.M]     *TD[1:cont.M,0]-TD[0,0]    *TD[1:cont.M,cont.M]) )/c4                     
    
    return P

In [26]:
P = Pressure()
P

array([[ 807138.14855568,  532123.59420796, -119130.15669053,
        -408106.73065246, -119130.15669053,  532123.59420796,
         807138.14855568],
       [ 807138.14855568,  532123.59420796, -119130.15669053,
        -408106.73065246, -119130.15669053,  532123.59420796,
         807138.14855568],
       [ 807138.14855568,  532123.59420796, -119130.15669053,
        -408106.73065246, -119130.15669053,  532123.59420796,
         807138.14855568],
       [ 807138.14855568,  532123.59420796, -119130.15669053,
        -408106.73065246, -119130.15669053,  532123.59420796,
         807138.14855568],
       [ 807138.14855568,  532123.59420796, -119130.15669053,
        -408106.73065246, -119130.15669053,  532123.59420796,
         807138.14855568],
       [ 807138.14855568,  532123.59420796, -119130.15669053,
        -408106.73065246, -119130.15669053,  532123.59420796,
         807138.14855568],
       [ 807138.14855568,  532123.59420796, -119130.15669053,
        -408106.73065246, -11913

In [27]:
def eigens_vel():
    eigen_vec_vel1  = np.zeros([cont.M,cont.M+1])
    eigen_val_vel1 = np.zeros([cont.M+1])
    eigen_vec_vel2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_vel2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])

    tempx[1:cont.M,1:cont.N]  = cont.asp*cont.asp*D2[1:cont.M,1:cont.N] 
    tempy[1:cont.N,1:cont.N]  =  cont.asp*cont.asp*TD2[1:cont.N,1:cont.N] 

    eigen_val_vel1[1:cont.M], eigen_vec_vel1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_vel2[1:cont.N], eigen_vec_vel2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N] )

    return eigen_vec_vel1, eigen_val_vel1, eigen_vec_vel2, eigen_val_vel2

In [28]:
eigens_vel()

(array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,  -6.73991097e-01,   6.89057421e-01,
           3.61643148e-01,   1.44584243e-01,  -2.70859758e-01,
           0.00000000e+00],
        [  0.00000000e+00,   1.99385166e-01,  -1.58744673e-01,
           4.30277879e-01,   4.89426948e-01,  -6.53173018e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -1.09376019e-01,  -7.32977268e-16,
          -6.06753955e-01,   6.92180120e-01,  -8.18104776e-16,
           0.00000000e+00],
        [  0.00000000e+00,   1.99385166e-01,   1.58744673e-01,
           4.30277879e-01,   4.89426948e-01,   6.53173018e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -6.73991097e-01,  -6.89057421e-01,
           3.61643148e-01,   1.44584243e-01,   2.70859758e-01,
           0.00000000e+00]]),
 array([   0.        , -298.79352021, -259.15338817,  -83.33679638,
      

In [29]:
def RHS_U():

    RHSU = cont.asp*D*P + 2*NL(U1,V1,U1)  - NL(U0,V0,U0) - (4*U1 - U0)/(2*cont.dt)
    RHSV = cont.asp*P*TD + 2*NL(U1,V1,V1) - NL(U0,V0,V0) - (4*V1 - V0)/(2*cont.dt) - cont.Ri*cont.Re*cont.Re*T2
    
    for j in range(1,cont.N):
        RHSU[:,j]= RHSU[:,j] - cont.asp*cont.asp*D2[:,0] *Uexact[0,j]   - cont.asp*cont.asp*D2[:,cont.N]*Uexact[cont.N,j] \
                             - cont.asp*cont.asp*Uexact[:,0] * TD2[0,j] - cont.asp*cont.asp*Uexact[:,cont.M]*TD2[cont.M,j]
        RHSV[:,j]= RHSV[:,j] - cont.asp*cont.asp*D2[:,0] *Vexact[0,j]   - cont.asp*cont.asp*D2[:,cont.N]*Vexact[cont.N,j] \
                             - cont.asp*cont.asp*Vexact[:,0] *TD2[0,j]  - cont.asp*cont.asp*Vexact[:,cont.M]*TD2[cont.M,j]
    return RHSU, RHSV

RHSU, RHSV = RHS_U()
np.shape(RHSU), np.shape(RHSV)
RHSU[1:5,1:5], RHSV[1:5,1:5]

(matrix([[-470517.58134256,   36657.8531192 ,  -10997.35593576,
             7331.57062384],
         [-470630.70659256,   36666.66666616,  -10999.99999984,
             7333.33333323],
         [-470630.70659909,   36666.66666667,  -11000.        ,
             7333.33333333],
         [-470630.70659256,   36666.66666616,  -10999.99999985,
             7333.33333323]]),
 matrix([[ -6.51925802e-09,  -1.07102096e-08,   7.03637134e-09,
            9.77888703e-09],
         [ -4.65661287e-09,  -8.38190317e-09,   6.81420876e-09,
            6.51925802e-09],
         [ -3.72529030e-09,  -9.31322575e-09,   7.04520380e-09,
            6.98491931e-09],
         [ -3.72529030e-09,  -8.84756446e-09,   7.27987005e-09,
            7.45058060e-09]]))

In [30]:
RHSU = cont.asp*D*P + 2*NL(U1,V1,U1)  - NL(U0,V0,U0) - (4*U1 - U0)/(2*cont.dt)
RHSV = cont.asp*P*TD + 2*NL(U1,V1,V1) - NL(U0,V0,V0) - (4*V1 - V0)/(2*cont.dt) - cont.Ri*cont.Re*cont.Re*T2

In [31]:
def Velocity():
    U = np.asmatrix(np.zeros([cont.M+1,cont.N+1]))
    V = np.asmatrix(np.zeros([cont.M+1,cont.N+1]))
    eig_vec1, eig_val1, eig_vec2, eig_val2 = eigens_vel()
    RHSU,RHSV = RHS_U()       
    sigma = 3.0*cont.Pr/(2.0*cont.dt)
    
    U=Helmholtz_solver(RHSU,sigma,eig_val1,eig_vec1,eig_val2,eig_vec2)
    V=Helmholtz_solver(RHSV,sigma,eig_val1,eig_vec1,eig_val2,eig_vec2)
    
    U = np.asmatrix(U)
    V = np.asmatrix(V)
    
    # impose exact boundary velocity    
    U[:,0] = Uexact[:,0] 
    V[:,0] = Vexact[:,0]
    U[:,cont.M] = Uexact[:,cont.M]
    V[:,cont.M] = Vexact[:,cont.N]
    U[0,:] = Uexact[0,:]  
    V[0,:] = Vexact[0,:]
    U[cont.N,:] = Uexact[cont.N,:]
    V[cont.N,:] = Vexact[cont.N,:]
    
    return U, V

In [32]:
U, V = Velocity()
U[1:5,1:5], V[1:5,1:5]
U,V

(matrix([[    0.        ,     0.        ,     0.        ,     0.        ,
              0.        ,     0.        ,     0.        ],
         [ 2749.33898394,   244.54942766,   -13.56155064,     4.53617978,
             -2.99910388,     5.28451241,     0.        ],
         [ 2749.99999996,   269.47201975,   -14.31723092,     4.87576477,
             -3.22302529,     5.66114829,     0.        ],
         [ 2750.        ,   267.04488208,   -14.22428799,     4.83928188,
             -3.19901212,     5.62025444,     0.        ],
         [ 2749.99999996,   269.47201975,   -14.31723092,     4.87576477,
             -3.22302529,     5.66114829,     0.        ],
         [ 2749.33898394,   244.54942766,   -13.56155064,     4.53617978,
             -2.99910388,     5.28451241,     0.        ],
         [    0.        ,     0.        ,     0.        ,     0.        ,
              0.        ,     0.        ,     0.        ]]),
 matrix([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
   

In [33]:
def eigens_phi():
    eigen_vec_phi1  = np.zeros([cont.M+1,cont.M+1])
    eigen_val_phi1 = np.zeros([cont.M+1])
    eigen_vec_phi2  = np.zeros([cont.N+1,cont.N+1])
    eigen_val_phi2 = np.zeros([cont.N+1])
    tempx = np.zeros([cont.M+1,cont.M+1])
    tempy = np.zeros([cont.N+1,cont.N+1])
  
    D00_MM_DM0_0M   = D[0,0]*D[cont.M,cont.M]   - D[cont.M,0]*D[0,cont.M]
    TD00_NN_TD0N_N0 = TD[0,0]*TD[cont.N,cont.N] - TD[0,cont.N]*TD[cont.N,0]
    
    for i in range(cont.M): # generate the coefficient matrix column-wise
        tempx[i,1:cont.M] = -D2[i,0] * (D[cont.M,cont.M]*D[0,1:cont.M]-D[0,cont.M]*D[cont.M,1:cont.M])/D00_MM_DM0_0M \
                          + D2[i,cont.M] * (D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M])/D00_MM_DM0_0M 
    ##tempx[1:cont.M,1:cont.N] = (D2[1:cont.M,1:cont.N] + tempx[1:cont.M,1:cont.N])
    tempx[1:cont.M,1:cont.N] = cont.asp**2*(D2[1:cont.M,1:cont.N] + tempx[1:cont.M,1:cont.N])
    
    for j in range(cont.M): # generate the coefficient matrix column-wise
        tempy[1:cont.N,j] = np.asarray(np.transpose(-(TD2[0,j] * (TD[cont.N,cont.N]*TD[1:cont.N,0]-TD[cont.N,0]*TD[1:cont.N,cont.N])/TD00_NN_TD0N_N0) \
                          + (TD2[cont.N,j] * (TD[0,cont.N]*TD[1:cont.N,0]-TD[0,0]*TD[1:cont.N,cont.N])/TD00_NN_TD0N_N0)))
    ##tempy[1:cont.M,1:cont.N] = (TD2[1:cont.M,1:cont.N] + tempy[1:cont.M,1:cont.N])
    tempy[1:cont.M,1:cont.N] = cont.asp**2*(TD2[1:cont.M,1:cont.N] + tempy[1:cont.M,1:cont.N])
    
    eigen_val_phi1[1:cont.M], eigen_vec_phi1[1:cont.M,1:cont.M] = np.linalg.eig(tempx[1:cont.M,1:cont.M])
    eigen_val_phi2[1:cont.N], eigen_vec_phi2[1:cont.N,1:cont.N] = np.linalg.eig(tempy[1:cont.N,1:cont.N])
    
    return eigen_vec_phi1, eigen_val_phi1, eigen_vec_phi2, eigen_val_phi2

In [34]:
eigens_phi()

(array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,  -2.48151635e-01,   4.93291351e-01,
          -5.59384051e-01,  -4.47213595e-01,  -5.72984105e-01,
           0.00000000e+00],
        [  0.00000000e+00,   5.57644495e-01,  -5.06619821e-01,
          -6.65576838e-03,  -4.47213595e-01,  -4.14353974e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -5.04882924e-01,  -1.79361931e-15,
           6.11629273e-01,  -4.47213595e-01,  -1.29169494e-15,
           0.00000000e+00],
        [  0.00000000e+00,   5.57644495e-01,   5.06619821e-01,
          -6.65576838e-03,  -4.47213595e-01,   4.14353974e-01,
           0.00000000e+00],
        [  0.00000000e+00,  -2.48151635e-01,  -4.93291351e-01,
          -5.59384051e-01,  -4.47213595e-01,   5.72984105e-01,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.

In [35]:
def RHS_phi(U,V):
    
    RHS = cont.asp*(D*U + V*TD)

    return RHS

In [36]:
RHS_phi(U, V)

matrix([[ -6.96455142e+04,  -6.01939300e+03,   3.38149643e+02,
          -1.12506723e+02,   7.43884362e+01,  -1.31199833e+02,
           0.00000000e+00],
        [ -1.90510323e+04,  -1.81500589e+03,   9.76621592e+01,
          -3.30803049e+01,   2.18681059e+01,  -3.84462229e+01,
          -2.43386805e-10],
        [  3.66402260e+03,   2.69314209e+02,  -1.64386918e+01,
           5.28861130e+00,  -3.49773409e+00,   6.20522961e+00,
          -2.49701786e-10],
        [ -5.30412358e-12,  -6.16977772e-11,   3.19623062e-11,
           2.21132463e-11,   2.29365574e-11,  -4.43495855e-11,
          -2.63438448e-10],
        [ -3.66402260e+03,  -2.69314209e+02,   1.64386918e+01,
          -5.28861130e+00,   3.49773409e+00,  -6.20522961e+00,
          -2.94747591e-10],
        [  1.90510323e+04,   1.81500589e+03,  -9.76621592e+01,
           3.30803049e+01,  -2.18681059e+01,   3.84462229e+01,
          -2.60353051e-10],
        [  6.96455142e+04,   6.01939300e+03,  -3.38149643e+02,
           1.

In [37]:
def correction(U,V,P):
    RHS = np.asmatrix(np.zeros([cont.M+1,cont.N+1]))
    phi = np.asmatrix(np.zeros([cont.M+1,cont.N+1]))
    
    RHS = RHS_phi(U,V)
    eig_vec1, eig_val1, eig_vec2, eig_val2 = eigens_phi()
    sigma = 0.0
    
    phi=Helmholtz_solver(RHS,sigma,eig_val1,eig_vec1,eig_val2,eig_vec2)
    
    phi[:,0] = 0
    phi[:,cont.M] = 0
    
    for j in range(1,cont.M):  # update the boundary of phi
        phi[0,j] = -np.dot(D[cont.N,cont.N]*D[0,1:cont.N]-D[0,cont.N]*D[cont.N,1:cont.N],phi[1:cont.M,j]) /c1
        phi[cont.N,j] = -np.dot(D[cont.M,0]*D[0,1:cont.M]-D[0,0]*D[cont.M,1:cont.M],phi[1:cont.M,j]) /c2
        
    for j in range(0,cont.M+1):
        phi[j,0] = -np.dot(phi[j,1:cont.M], TD[cont.M,cont.M]*TD[1:cont.M,0]-TD[cont.M,0]*TD[1:cont.M,cont.M]) /c3
        phi[j,cont.M] = -np.dot(phi[j,1:cont.M], TD[0,cont.M]*TD[1:cont.M,0]-TD[0,0]*TD[1:cont.M,cont.M]) /c4
    
            
    P2 = P + 3*(cont.Pr/(2*cont.dt))*phi
    U2 = U - 2*D *phi
    V2 = V - 2*phi *TD
            
    return U2, V2, P2, phi        

In [38]:
U2, V2, P2, phi = correction(U,V,P)

In [39]:
U2[1:5,1:5]

matrix([[ 140.8010344 ,  -42.61082788,   -3.3636898 ,   -7.2658949 ],
        [ 147.85894648,  -68.03212267,  -17.69022082,  -16.12782245],
        [ 231.31552205,  -63.55551701,  -24.49295013,  -20.4750244 ],
        [ 147.85894648,  -68.03212267,  -17.69022082,  -16.12782245]])

In [40]:
V2[1:6,1:5]

matrix([[ -9.48223010e+01,  -9.14907581e+01,  -1.82993009e+01,
          -1.37587370e+01],
        [ -1.37932730e+01,  -2.79373058e+01,  -1.81554874e+01,
          -5.73813557e+00],
        [ -4.06900821e-12,   1.27195554e-13,  -3.93769771e-12,
           1.83078119e-14],
        [  1.37932730e+01,   2.79373058e+01,   1.81554874e+01,
           5.73813557e+00],
        [  9.48223010e+01,   9.14907581e+01,   1.82993009e+01,
           1.37587370e+01]])

In [41]:
P2

array([[ 881926.68599148,  600556.83595658,  -85549.09152435,
        -393138.31513898, -110519.99697603,  540113.51264626,
         815846.27104207],
       [ 875198.97518162,  594690.98021276,  -87136.6886137 ,
        -393547.86771342, -110739.20166882,  539804.87728449,
         815406.0509191 ],
       [ 833592.72643784,  557837.83592899,  -99804.38013435,
        -397943.47759138, -113198.92417662,  537080.818708  ,
         812001.39357412],
       [ 807138.14855569,  532123.59420797, -119130.15669053,
        -408106.73065246, -119130.15669053,  532123.59420796,
         807138.14855568],
       [ 780683.57067353,  506409.35248694, -138455.93324671,
        -418269.98371354, -125061.38920444,  527166.36970793,
         802274.90353725],
       [ 739077.32192975,  469556.20820317, -151123.62476736,
        -422665.5935915 , -127521.11171224,  524442.31113144,
         798870.24619226],
       [ 732349.61111989,  463690.35245935, -152711.2218567 ,
        -423075.14616594, -12774

In [42]:
def int_vector():
    cont.M = 6
    W = np.zeros([cont.M+1])
    W[0] = 1.0/((cont.M**2) - 1.0)
    W[-1] = W[0]
    for j in range(1,cont.M):
        for i in range(1,int((cont.M/2))):
            W[j] = W[j] + 2.0/(1.0-4.0*(i**2)) * np.cos(2.0*i*j*np.pi/float(cont.M))
        W[j] = 1.0 + W[j] + np.cos(j*np.pi)/(1.0-(float(cont.M)**2.0))
        W[j] = (2.0/float(cont.M)) * W[j]
                              
    return W

In [43]:
W = int_vector()
W

array([ 0.02857143,  0.25396825,  0.45714286,  0.52063492,  0.45714286,
        0.25396825,  0.02857143])

In [44]:
float(2)


2.0

In [54]:
def energy(U2,V2):
    W = int_vector()
    U2 = np.asarray(U2)
    V2 = np.asarray(V2)
    
    E = 0.25*(np.dot(W,np.matmul(W,(U2*U2 + V2*V2)))/cont.Re**2)
    
    return E

In [55]:
energy(U2,V2)

0.01361766455761875